# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import leads.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('card_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(code='Invalid_card_number', message="Card Number must be contain digital or X T W'\n                     and have length from 8 to 15 characters", regex='^[XTW0-9]{8,15}$')])),
                ('expiry_date', models.DateField(blank=True, null=True, validators=[leads.validators.ExpiryDateValidator])),
                ('professional', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='language',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='leads.Lead'),
        ),
    ]
